package com.highcode.Rental_tool.web.exception;

public enum ExceptionType {
    DATA_UNIQUENESS_EXCEPTION,
    MY_RESOURCE_NOT_FOUND_EXCEPTION,
    RESOURCE_ALREADY_EXISTS_EXCEPTION,
    USER_ASSIGNED_EXCEPTION,
    ACCESS_FORBIDDEN_EXCEPTION,
    SENDING_MAIL_FAILED,
}
